added project templates for hook and step definitions
SpecFlowOSS/SpecFlow.VS pull request #16
Opened 2021-11-01 11:02 UTC by JordanWestern

2021-11-01 11:34 UTC, gasparnagy requested changes
Please see my changes below.

2021-11-01 11:34 UTC, gasparnagy commented on SpecFlow.VisualStudio.ItemTemplates/Hooks/Hooks_CSharp.vstemplate
> +	<WizardExtension>
The Wizard reference is not valid here, because the hooks template does not need a wizard logic (unless we want to add a dummy wizard logic to track the usage statistics).

2021-11-01 11:34 UTC, gasparnagy commented on SpecFlow.VisualStudio.ItemTemplates/Hooks/Hooks_VB.vstemplate
> +	<WizardExtension>
Like above, the wizard is not needed/valid here.

2021-11-01 11:34 UTC, gasparnagy commented on SpecFlow.VisualStudio.ItemTemplates/Hooks/Hooks1.cs
> +
This is fine, but it would be great to also demonstrate, how to make a hook that is filtered for a tag. Maybe we could add a third one here, like

```
[BeforeScenario("@sometag")]
public void FiltetredHook()... 
```

2021-11-01 12:06 UTC, JordanWestern commented on SpecFlow.VisualStudio.ItemTemplates/Hooks/Hooks1.cs
> +
Updated, also included an example of ordering, thought this might be useful also

2021-11-01 12:06 UTC, JordanWestern commented on SpecFlow.VisualStudio.ItemTemplates/Hooks/Hooks_VB.vstemplate
> +	<WizardExtension>
removed

2021-11-01 12:07 UTC, JordanWestern commented on SpecFlow.VisualStudio.ItemTemplates/Hooks/Hooks_CSharp.vstemplate
> +	<WizardExtension>
removed

2021-11-02 09:09 UTC, gasparnagy requested changes
The hooks look fine (you can consider adding the additional `@` sign as mentioned below. 

But it seems that my other review comment was not saved properly by GitHub, that was more important:

While the hook template is fine and makes sense, the step definition template is unnecessary IMHO, since we have the "define steps" command. Actually this template was introduced in the old VS extension when there was no such command, so the only way yo make a new step definition was to use the template. 

But with the "define steps" in place, I cannot really imagine a useful scenario when someone would use that (rather the opposite, because it suggests that you should write your regular expressions manually), so my suggestion is not to add this template (remove it from the PR).

In general I had to learn that the calculator example is pretty confusing for many people and this is why I removed it from the "add new feature file" template. Using the calculator steps in this template is probably even more confusing...

2021-11-02 11:48 UTC, gasparnagy approved these changes

2021-11-02 12:19 UTC, merged