Implement new SpecFlowConnector
SpecFlowOSS/SpecFlow.VS pull request #66
Opened 2022-02-15 12:23 UTC by patiqs

2022-02-18 10:29 UTC, gasparnagy requested changes
Thx. See my smaller notes at the code lines.

2022-02-18 10:29 UTC, gasparnagy commented on SpecFlow.VisualStudio.SpecFlowConnector/SpecFlowProxies/DynamicRuntimePluginLoaderFactory.cs
> +public class DynamicRuntimePluginLoaderFactory
Find a better name for this. The point is not that it is dynamic, but that it can create a plugin loader that is compatible to the old SpecFlow loader interface. So probably we should put the SF version to the name.

2022-02-18 10:29 UTC, gasparnagy commented on Tests/SpecFlow.VisualStudio.SpecFlowConnector.Tests/ApprovalTestData/ConnectorOptionsParse/ConnectorOptionsParseTests.Approval.debug.approved.txt
> +﻿Right`2[System.Exception,SpecFlow.VisualStudio.SpecFlowConnector.ConnectorOptions]DiscoveryOptions { DebugMode = True, AssemblyFile = C:\git\SpecFlow.VS\Tests\SpecFlow.VisualStudio.SpecFlowConnector
Fix paths in the approved file?

2022-02-18 10:29 UTC, gasparnagy commented on Tests/SpecFlow.VisualStudio.SpecFlowConnector.Tests/ApprovalTestData/ConnectorOptionsParse/ConnectorOptionsParseTests.Approval.Invalid_command.approved.txt
> +﻿Left`2[System.Exception,SpecFlow.VisualStudio.SpecFlowConnector.ConnectorOptions]System.ArgumentException: Invalid command: xxx
My fear is that this *Left`2* kind of things will cause maintenance problems with the approval tests. The test should be able to understand the error (regardless of how it was wrapped) and make the approval independent of the wrapping.

2022-02-18 10:29 UTC, gasparnagy commented on Tests/SpecFlow.VisualStudio.SpecFlowConnector.Tests/ApprovalTestData/DumpException/DumpExceptionTests.Approval.NestedAggregateException.approved.txt
> +  at ... in ...
Same here. Are we really want to expected this exact exception nesting?
About the error handling tests, it feels that we have used approval testing for unit testing (where we should follow the single assertion principle).

2022-02-18 10:29 UTC, gasparnagy commented on Tests/SpecFlow.VisualStudio.SpecFlowConnector.Tests/ApprovalTestData/GeneratedProjectTests/DS_3.9.40_nunit_nprj_net35_bt_992117478.approved.txt
> +    {
It seems that this approval file was not updated to the new style (step defs included)

2022-02-18 10:29 UTC, gasparnagy commented on Tests/SpecFlow.VisualStudio.SpecFlowConnector.Tests/GeneratedProjectTests.cs
> +    //[InlineData("DS_3.9.40_nunit_nprj_net35_bt_992117478")]
remove thses or comment why they are disabled

2022-02-18 10:29 UTC, gasparnagy commented on Tests/SpecFlow.VisualStudio.Specs/Features/Discovery/DiscoverySpecFlowVersionCompatibility.feature
> +	| line-v3.9.40 | v3.9.40  |
The "line" in the description refers to a product line, like v3.9.* that we usually test with the latest patch. So instead of adding a new line, I would just change the version of the "line-v3.9" from v3.9.22 to v3.9.40.
If there is a specific reason to keep the 3.9.22 as test, then move it to scenario "Regression tests for special discovery combinations"

2022-02-18 10:29 UTC, gasparnagy commented on SpecFlow.VS.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "SpecFlow.VisualStudio.SpecFlowConnector", "SpecFlow.VisualStudio.SpecFlowConnector\SpecFlow.VisualStudio.SpecFlowConnector.csproj", "{5E709910-1EC
I think we should include these connector related projects to the "Connectors" and the "Connectors/Tests" solution folder.

2022-03-18 15:18 UTC, patiqs commented on SpecFlow.VisualStudio.SpecFlowConnector/Discovery/DiscoveryOptions.cs
> +    public static Either<Exception, ConnectorOptions> Parse(string[] args, bool debugMode)
Modified to throw exceptions

2022-03-18 15:20 UTC, patiqs commented on SpecFlow.VisualStudio.SpecFlowConnector/Runner.cs
> +        catch (Exception ex)
Modified to throw exceptions

2022-03-18 15:24 UTC, patiqs commented on Tests/SpecFlow.VisualStudio.SpecFlowConnector.Tests/ApprovalTestData/DumpException/DumpExceptionTests.Approval.NestedAggregateException.approved.txt
> +  at ... in ...
obsolete files. Deleted

2022-03-20 08:36 UTC, patiqs commented on Tests/SpecFlow.VisualStudio.SpecFlowConnector.Tests/GeneratedProjectTests.cs
> +    //[InlineData("DS_3.9.40_nunit_nprj_net35_bt_992117478")]
Removed. We don't test against .NET 3.5

2022-03-20 08:37 UTC, patiqs commented on SpecFlow.VisualStudio.SpecFlowConnector/Discovery/BindingRegistryFactoryProvider.cs
> +            if (ver >= 2_00_000) return ver;
Removed this check

2022-03-20 08:37 UTC, patiqs commented on SpecFlow.VisualStudio.SpecFlowConnector/Runner.cs
> +                //.Map(result=>result.MapLeft(errorMessage => new Exception(errorMessage)))
removed

2022-03-20 16:34 UTC, patiqs commented on SpecFlow.VisualStudio.SpecFlowConnector/Runner.cs
> +            .Map(x => x.assembly.GetType(x.typeName)!)
TypeFromAssemblyLoadContext

2022-03-20 16:35 UTC, patiqs commented on SpecFlow.VisualStudio.SpecFlowConnector/Runner.cs
> +                    .Reduce(new RunnerResult(null!, $"Unable to deserialize{s}")))
Changed

2022-03-20 16:35 UTC, patiqs commented on SpecFlow.VisualStudio.SpecFlowConnector/Runner.cs
> +    }
Changed

2022-04-21 20:29 UTC, patiqs commented on Tests/SpecFlow.VisualStudio.Specs/Features/Discovery/DiscoverySpecFlowVersionCompatibility.feature
> +	| line-v3.9.40 | v3.9.40  |
Chaged

2022-04-21 20:33 UTC, patiqs commented on SpecFlow.VS.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "SpecFlow.VisualStudio.SpecFlowConnector", "SpecFlow.VisualStudio.SpecFlowConnector\SpecFlow.VisualStudio.SpecFlowConnector.csproj", "{5E709910-1EC
Moved

2022-05-04 06:00 UTC, gasparnagy approved these changes

2022-05-04 06:00 UTC, merged